// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSUh5c_JTPCfetZmjU7775nMjCzI1ut7s',
    appId: '1:610923748533:web:fa2b978b7872feb985f2fc',
    messagingSenderId: '610923748533',
    projectId: 'calcho-8bd47',
    authDomain: 'calcho-8bd47.firebaseapp.com',
    storageBucket: 'calcho-8bd47.firebasestorage.app',
    measurementId: 'G-48YEHNKEP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtJcjmQhJ6c2qENgQUG45Cvf_1L9Oa1NE',
    appId: '1:610923748533:android:6a4299dafd21822885f2fc',
    messagingSenderId: '610923748533',
    projectId: 'calcho-8bd47',
    storageBucket: 'calcho-8bd47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtnq4g8mz3CCWTCYzAy0f4AZiXUJ0WQ2U',
    appId: '1:610923748533:ios:2a0f8aba7ff96ec785f2fc',
    messagingSenderId: '610923748533',
    projectId: 'calcho-8bd47',
    storageBucket: 'calcho-8bd47.firebasestorage.app',
    iosBundleId: 'com.sazzon.calcho',
  );
}
